# Generated by Django 3.1 on 2020-08-19 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoastBoastModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roast_boast', models.BooleanField()),
                ('content', models.CharField(max_length=280)),
                ('up_vote', models.IntegerField()),
                ('down_vote', models.IntegerField()),
                ('submit_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
